package com.elmakers.mine.bukkit.plugins.magic;


public enum SpellResult {
	CAST, 
	AREA,
	FAIL, 
	INSUFFICIENT_RESOURCES, 
	INSUFFICIENT_PERMISSION, 
	COOLDOWN, 
	NO_TARGET, 
	TARGET_SELECTED,
	PLAYER_REQUIRED,
	COST_FREE;
	
	public static SpellResult[] FAILURES = { FAIL, INSUFFICIENT_RESOURCES, INSUFFICIENT_PERMISSION, COOLDOWN, NO_TARGET };
}
