liminal_base:
  # This is a base config inherited by other liminal world configs
  # It does not itself generate a world
  world: ""
  ground_level: 1
  autoload: true
  bedrock_level: 0
  spawn: 0,2,0
  game_mode: adventure
  leave_game_mode: survival
  title_delay: 2000
  respawn: world_concrete
  game_rules:
    advance_weather: false
    advance_time: false
    spawn_mobs: false
    spawn_monsters: false
    spawn_phantoms: false
    spawn_patrols: false
    command_block_output: false
    command_blocks_work: true
