#
# These options are applied to all spells by default.
#
default:
    # Spells take 15 minutes to return to full SP earning potential
    earns_cooldown: 900000
    # Enable this to prevent spell casts outside the world border
    world_border_restricted: false
    effects:
       target_selected:
       - class: EffectSingle
         location: origin
         sound: magic.hit
         sound_volume: 0.5
       - class: EffectSingle
         location: target
         use_block_location: true
         color_override: color
         effectlib:
           class: CubeEffect
           iterations: 15
           particle: redstone
           color: "00FFAA"
           edge_length: 1.2
           enable_rotation: false
           offset: 0.5,0.5,0.5
       - class: EffectTrail
         particle: spell_mob
       fail:
       - class: EffectSingle
         location: origin
         sound: block_note_block_basedrum
         sound_broadcast: false
         sound_volume: 0.8
         sound_pitch: 1.2
       insufficient_resources:
       - class: EffectSingle
         location: origin
         sound: block_note_block_bass
         sound_broadcast: false
         sound_volume: 0.7
         sound_pitch: 1.2
       insufficient_permission:
       - class: EffectSingle
         location: origin
         sound: block_note_block_bass
         sound_broadcast: false
         sound_volume: 0.9
         sound_pitch: 1.5
       cooldown:
       - class: EffectSingle
         location: origin
         sound: block_note_block_basedrum
         sound_broadcast: false
         sound_volume: 0.6
         sound_pitch: 0.8
       cursed:
       - class: EffectSingle
         location: origin
         entity_effect: hurt
       backfire:
       - class: EffectSingle
         location: origin
         entity_effect: hurt
       blocked:
       - class: EffectSingle
         location: origin
         entity_effect: hurt
       upgrade:
       - class: EffectSingle
         location: origin
         sound: entity_player_levelup
         firework: ball_large
       progress:
       - class: EffectSingle
         location: origin
         sound: entity_player_levelup
         firework: ball_large
       break:
       - class: EffectSingle
         location: target
         effect: step_sound
       earn_sp:
       - class: EffectSingle
         location: origin
         sound: entity_player_levelup
         sound_volume: 0.6
         sound_pitch: 0.75
       - class: EffectSingle
         location: origin
         sound: entity_experience_orb_pickup
         sound_volume: 0.4
         sound_pitch: 1.5
       earn_scaled_sp:
       - class: EffectSingle
         location: origin
         sound: entity_experience_orb_pickup
         sound_volume: 0.6
         sound_pitch: 1.5
       reflect:
       - class: EffectSingle
         location: target
         particle: fireworks_spark
         particle_count: 3
         particle_offset_x: 0.1
         particle_offset_y: 0.1
         particle_offset_z: 0.1
         sound: magic.shimmer_quiet
       headshot: hit
       cast_self: cast
       no_target: cast
       no_action: cast
       alternate: cast
       alternate_up: cast
       alternate_down: cast
       alternate_sneak: cast
       fizzle: fail
       cancelled: fail
       entity_required: fail
       living_entity_required: fail
       player_required: fail
       location_required: fail
       world_required: fail
       invalid_world: fail

