base:
  storage:
    mana: class
    mana_max: class
    mana_regeneration: class
    mana_timestamp: class
    spell_levels: class
    spells: class
    brushes: class
    path: subclass
    hotbar_count: subclass

    # Attributes are primarily stored on the mage
    # But attributes can also be set on wands to provide attribute buffs.
    attributes: mage,wand

