# This is mostly here for the liminal RP, the rest are identical at the time of this config creation
alternate_resource_packs:
  default:
    url: "http://rp.elmakers.com/Magic-RP-26.1.zip"
  borders:
    url: "http://rp.elmakers.com/Magic-potter-RP-26.1.zip"
  painterly:
    url: "http://rp.elmakers.com/Magic-painterly-RP-26.1.zip"
  lowres:
    url: "http://rp.elmakers.com/Magic-lowres-RP-26.1.zip"
  skulls:
    url: "http://rp.elmakers.com/Magic-skulls-RP-26.1.zip"
    url_icons_enabled: true
  survival:
    url: "http://rp.elmakers.com/Magic-RP-26.1.zip"
  all:
    url: "http://rp.elmakers.com/Magic-all-RP-26.1.zip"
  modelengine:
    url: "http://rp.elmakers.com/Magic-modelengine-RP-26.1.zip"
  hires:
    url: "http://rp.elmakers.com/Magic-hires-RP-26.1.zip"
  hires-all:
    url: "http://rp.elmakers.com/Magic-hires-all-RP-26.1.zip"
  liminal:
    url: "http://rp.elmakers.com/Magic-liminal-RP-26.1.zip"
  liminal-all:
    url: "http://rp.elmakers.com/Magic-liminal-all-RP-26.1.zip"
  hires-modelengine:
    url: "http://rp.elmakers.com/Magic-hires-modelengine-RP-26.1.zip"
  hires-robes:
    url: "http://rp.elmakers.com/Magic-hires-robes-RP-26.1.zip"
  robes:
    url: "http://rp.elmakers.com/Magic-robes-RP-26.1.zip"
  valhalla:
    url: "http://rp.elmakers.com/Magic-valhalla-RP-26.1.zip"
  vanilla:
    url: "http://rp.elmakers.com/Magic-vanilla-RP-26.1.zip"
  vanilla-all:
    url: "http://rp.elmakers.com/Magic-vanilla-all-RP-26.1.zip"
  vanilla-robes:
    url: "http://rp.elmakers.com/Magic-vanilla-robes-RP-26.1.zip"
  war:
    url: "http://rp.elmakers.com/Magic-war-RP-26.1.zip"
