package com.elmakers.mine.bukkit.api.wand;

public enum WandAction {
    NONE, CAST, TOGGLE, CYCLE, CYCLE_REVERSE, CYCLE_HOTBAR, CYCLE_HOTBAR_REVERSE, REPLACE,

    TOGGLE_ICON,

    CYCLE_BRUSH, CYCLE_BRUSH_REVERSE,

    CYCLE_ACTIVE_HOTBAR, CYCLE_ACTIVE_HOTBAR_REVERSE,

    ALT_CAST, ALT_CAST2, ALT_CAST3, ALT_CAST4, ALT_CAST5, ALT_CAST6, ALT_CAST7,

    DESTROY,

    CANCEL
}
